version: 2.1
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: mule
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_VERSION: 4.3.0
          MULE_APP_NAME: test-circle-ci
          MULE_ENV: DEV
          MULE_WORKER_TYP: MICRO
          MULE_WORKER: 1
    steps:
      - checkout
      - restore_cache:
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - save_cache:
          paths:
            - ~/.m2
          key: 'mulesoft-ci-cd-{{ checksum "pom.xml" }}'
      - run:
          name: Build
          command: |
            mvn clean compile -s settings.xml
      - run:
          name: mUnit Test
          command: |
            mvn clean test -s settings.xml
      - run:
          name: artifactory deployment
          command: |
            mvn clean deploy -s settings.xml
      - run:
          name: cloudhub deployment
          command: |
            mvn -s settings.xml clean deploy -DmuleDeploy -DMULE_ENV=${anypoint.environment} -DMULE_APP_NAME=${anypoint.appName} -DMULE_WORKER_TYP=${anypoint.workerType} -DMULE_WORKER=${anypoint.workers} -DMULE_USERNAME=${anypoint.username} -Dcentral_password=${anypoint.password}